### ISSUE TITLE
Snippets with exact prefixes matches should appear first

### ISSUE THREAD

**Issue by maxbrunsfeld** [atom-community/autocomplete-snippets#48] opened 2015-04-21 18:42 UTC
For example, if the text before the cursor is `i`, a snippet with the prefix `i` (e.g. `it block` from language-coffee-script) should appear above a snippet with a longer prefix (e.g. `idea` from language-todo). Currently, the `idea` snippet is first.

**Comment by joefitzgerald** [comment] 2015-04-21 19:06
:+1:

**Comment by joefitzgerald** [comment] 2015-04-21 22:10
@maxbrunsfeld related: #47.

**Comment by joefitzgerald** [comment] 2015-04-21 22:12
Duplicate of #43.

**Closed by joefitzgerald** 2015-04-21 22:12 UTC
Labels: duplicate
